### ISSUE TITLE
The value fxFlex "1 0 auto" translates to css  flex: 1 1 auto

### ISSUE THREAD

**Issue by somombo** [angular/flex-layout#120]
See https://plnkr.co/edit/itCtZRcTBzc5DRAIBoPF :

`fxFlex="1 0 auto"` 

results in 

```css
.css { 
  flex: 1 1 auto; 
  /* ... */ 
} 
```

This can't be right?
