### ISSUE TITLE
The order of the values of fxLayoutAlign is the opposite of place-content

### ISSUE THREAD

**Issue by Maroon1** [angular/flex-layout#452]
suppose we set `fxLayoutAlign="center stretch"`, and the value of `place-content` is `stretch center`.

``` html
<div fxLayoutAlign="center stretch"></div>
```

```css
div {
  place-content: stretch center;
}
```
