### ISSUE TITLE
Media queries via (s)CSS

### ISSUE THREAD

**Issue by kurtommy** [angular/flex-layout#783]
# Feature Request

#### What is the desired behavior?
Use media query via mixin in CSS

#### What is the use-case or motivation for the desired behavior?
From what i've read in the DOC if i want a style eg a button with different background color based on breakpoints i can only do something like

`<button [ngClass.xs]="xs-button" [ngClass.xs]="md-button">HI!</button>`

and in CSS
```css
.xs-button {
  background-color: red;
}
.md-button {
  background-color: red;
}
```

This surely works but leads a lot of pollution in the markup, could you also export a mixins to do the below?

With CSS media query:

`<button>HI!</button>`

```css

button {
  background-color: yellow;
  @include media-breakpoint(xs) {
     background-color: red;
   }
  @include media-breakpoint(md) {
    background-color: blue;
   }
}
```

I can of course crate a set of mixins to do the above but would be great if this would exposed by flex-layout matching configured breakpoints..

Thanks
