### ISSUE TITLE
Utilizing the Responsive API to manage container height

### ISSUE THREAD

**Issue by cschroeter** [angular/flex-layout#86]
Is there a way to use the responsive API to set the height of a container?
At the moment I manage the height of the container like this:

```scss
section {
  height: 680px;
  @include xs {
    height: 100vh;
  }
}
```

```html
<section id="s1" fxLayoutAlign="center">
  <img src="../assets/logo.svg" alt="Logo">
</section>
```
